title: "Chidi Prince John"
tagline: ""
description: ""
author: "Chidi Prince John"
email: "chidiprincejohn@gmail.com"

url: "https://bychidijohn.github.io"
baseurl: ""

github_username: "bychidijohn"
linkedin_username: "https://www.linkedin.com/in/chidiebere-john/"
twitter_username: ""
google_scholar: ""

markdown: kramdown
highlighter: rouge
permalink: /:title/
timezone: America/Los_Angeles

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  smart_quotes: ["lsquo", "rsquo", "ldquo", "rdquo"]

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - .gitignore

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
